name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: gradle-${{ runner.os }}-

    - name: Install Android command-line tools
      run: |
        mkdir -p ${{ github.workspace }}/android-sdk/cmdline-tools
        cd ${{ github.workspace }}/android-sdk
        curl -s -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q cmdline-tools.zip -d cmdline-tools
        rm cmdline-tools.zip
        mkdir -p cmdline-tools/latest
        # Move extracted contents into 'latest' folder (some zips already contain a top-level folder)
        if [ -d cmdline-tools/cmdline-tools ]; then
          mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/ || true
        else
          mv cmdline-tools/* cmdline-tools/latest/ || true
        fi

    - name: Install SDK packages
      env:
        ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ env.PATH }}
      run: |
        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Build Debug APK
      env:
        ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ env.PATH }}
      run: ./gradlew :app:assembleDebug --no-daemon

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
